### PR TITLE
Fix replenish clip-only for M4A1-S

### PR DESCRIPTION
**Pull request by Blacktail92**
- replaced CSWeapon_M4A1_SILENCER with CSWeapon_NEGEV
- recompiled the plugin with SourceMod Version: 1.11.0.6653

### CODE REVIEW

**Comment by Maxximou5** [comment]
What issue are you experiencing with clip only replenish with the M4A1-S?

**Comment by Blacktail92** [comment]
> What issue are you experiencing with clip only replenish with the M4A1-S?

It restores clip back to 20 instead of 25 and furthermore, if `dm_replenish_ammo_type` is 2 or 3, reserve ammo gets restored to 40 as well. A temporary fix was to replace `int sequence = weaponId == CSWeapon_M4A1_SILENCER ? 1 : 0;` with `int sequence = weaponId == CSWeapon_NEGEV ? 1 : 0;`; so I did and negev did not get affected.

**Comment by Maxximou5** [comment]
Those changes have nothing to do with clip management. If you're trying to adjust the clip size, you simply change the amount.
https://github.com/Maxximou5/csgo-deathmatch/blob/3eec9a5c59d6fb89973e8c4ab3a8ea298315ee19/scripting/deathmatch.sp#L2045
https://github.com/Maxximou5/csgo-deathmatch/blob/3eec9a5c59d6fb89973e8c4ab3a8ea298315ee19/scripting/deathmatch.sp#L2071
https://github.com/Maxximou5/csgo-deathmatch/blob/3eec9a5c59d6fb89973e8c4ab3a8ea298315ee19/scripting/deathmatch.sp#L2116-L2117

**Comment by Blacktail92** [comment]
The lines you mentioned were the same and also correct from the beginning. So I did not touch them. Anyways, I put back `CSWeapon_M4A1_SILENCER` and checked aformentioned lines once more and this time `dm_replenish_ammo_type 1` worked fine but now there is this other bug where if `dm_replenish_ammo_type 2` or `dm_replenish_ammo_type 3` and you kill somebody then reload; reserve ammo for m4a1s gets restored to 40. 

Just a note, `sv_infinite_ammo` was `0` this whole time for testing purposes. Nevertheless, I'm closing this pr since there is no need for it.

**Pull request closed without merging**
