### PR TITLE
Update Translations Portuguese-BR & Fix Spawns

### PR DESCRIPTION
**Pull request by crashzk**
- Add Templates Issues;
- Add Spawns **`de_vertigo`**;
- Add Spawns **`de_ancient`**;
- Add Issue Templates;
- Update Translations Portuguese-BR;
- Update Readme;
- Fix Spawns **`de_cache`**;
- Fix Spawns **`de_nuke`**;
- Fix Spawns **`de_mirage`**;
- Fix Spawns **`de_cbble`**;
- Removed repeated translation **`"Guns Menu"`**;

### CODE REVIEW

**Comment by crashzk** [comment]
Added new spawns for missing maps and fixed some of other maps.

**Comment by crashzk** [comment]
@Maxximou5 I believe it can be merged without problems.

**Comment by crashzk** [comment]
@Maxximou5 can this PR be merged?

**Comment by Maxximou5** [comment]
Closing all v2 requests which will be replaced with v3.

**Pull request closed without merging**
